### ISSUE TITLE
Deployment en Netlify

### ISSUE THREAD

**Issue by ShayBRJ** [ULL-ESIT-DMSI-2324/nextjs-borja-medina-ramos-alu0101337609#3]
Buenas @crguezl, le quería comentar que al intentar hacer el despliegue en Netlify por motivo de permisos del propietario me se me deniega realizarlo.  Si me los pudiera dar para continuar con la práctica se lo agradecería.
Saludos y disculpe las molestias!

**Comment by ShayBRJ** [comment]
Probé con ambas visibilidades y en ambas me pide permisos.
Le adjunto una imagen con el problema incluso después de ponerlo como visibilidad pública.
![despliegue-netlify](https://github.com/ULL-ESIT-DMSI-2324/nextjs-borja-medina-ramos-alu0101337609/assets/72421634/0951b539-04fd-4d66-baff-dfd5edab1e8d)

**Comment by crguezl** [comment]
@ShayBRJ 

Es extraño porque Netlify debería tener permisos:

<img width="701" alt="Captura de pantalla 2023-12-04 a las 19 56 24" src="https://github.com/ULL-ESIT-DMSI-2324/nextjs-borja-medina-ramos-alu0101337609/assets/1142554/1dc8cd56-5405-4fcb-983e-c7396df2da87">

**Comment by crguezl** [comment]
En la imagen que envías parece que no hubieras cliqueado en el repo. Obviamente tu no tienes permisos sobre la org pero si sobre el repo

**Comment by crguezl** [comment]
He hecho la prueba con el alumno de prueba y he podido desplegar en netlify la app

<img width="1231" alt="Captura de pantalla 2023-12-05 a las 8 37 04" src="https://github.com/ULL-ESIT-DMSI-2324/nextjs-borja-medina-ramos-alu0101337609/assets/1142554/db726d64-5100-433c-bc63-cf92447c8363">

**Comment by ShayBRJ** [comment]
@crguezl Buenos días! Lo acabo de intentar nuevamente y me ha dejado hacer el despliegue.
Muchas gracias y saludos 👍
